### ISSUE TITLE
Scheduled Publishing dialog - button 'Ok' is not available, when the dialog is opened on laptop

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#289]
1. Select a site and click on `Schedule...`

**Issue** - Ok button for `Online to` is not available

![image](https://user-images.githubusercontent.com/3728712/42268587-91c34c8e-7f84-11e8-85de-f9c4e8cde48f.png)

**Comment by alansemenov** [comment]
The button is there but the dropdown is cut off due to screen height and there's no scrollbar. On mobile it's even worse (see below). We should do the same thing we do for regular dropdowns - calculate space below and above and see where the div will fit. If neither space is available, open underneath but with a scrollbar. 

![image](https://user-images.githubusercontent.com/11612490/42270126-5d91d0c4-7f80-11e8-8c74-3b0ea012a0ec.png)

**Comment by edloidas** [comment]
Issue moved to [enonic/lib-admin-ui #674](https://github.com/enonic/lib-admin-ui/issues/674) via [**ZenHub**](https://www.zenhub.com/)
