### ISSUE TITLE
LiveEdit Frame - Wrapper div element is missing for a new fragment until the page is refreshed

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#33]
@sgauruseu commented on [Tue Feb 20 2018](https://github.com/enonic/xp-apps/issues/605)

 2 ui-tests fails, due to changes in the DOM.

1. Start to add a site , select Features, type a name 
3. select 'main region' in controller-dropdown
4. open Page Component and insert an existing fragment 

Issue - element `<div>` with styles is missed when the fragment has been selected:

<img width="770" alt="frragment1" src="https://user-images.githubusercontent.com/3728712/36426431-00581f6e-165b-11e8-891e-a33ed872b6d6.png">

**Refresh the page in browser, the required div appears:**

<img width="925" alt="fragm2" src="https://user-images.githubusercontent.com/3728712/36426513-3c969140-165b-11e8-8cc4-86ef7e146ca6.png">

**Comment by jsi** [comment]
Tests are still failing due to this bug.

**Comment by aro** [comment]
The div wrapper is not there when the page is rendered outside LiveEdit. I think if anything, then the div wrapper should not be added in the first place.

For what I can see the HTML sent from the server does not included the wrapper. Looks like it is added in the front-end somehow.

**Comment by sigdestad** [comment]
Hmm... can it be that this wrapper is related to DragNDrop - not sure why we would need it either?

**Comment by aro** [comment]
When the page is rendered in edit mode the fragment is rendered with a wrapper, and inside there is the part element:

```
<div data-portal-component-type="fragment">
	<div data-portal-component-type="part">
	...
	</div>
</div>
```

When the page is rendered live, the "fragment" wrapper is removed, since this was only artificially added so that Live Edit can locate the components.
```
<div data-portal-component-type="part">
	...
</div>
```

While in live edit, if the user adds a fragment, it fetches the component rendered on the server, which does not have the extra wrapper (like in live mode).

So this are the cases:
- Live rendering: no wrapper
- Edit mode rendering of added component: no wrapper
- Edit mode reload rendering: added wrapper

We need the wrapping div of the Fragment for Live Edit.
We looked into this and discussed it before with @vbradnitski and concluded that it was a minor thing that is not a real issue in practice(just for our internal UI test) and it was better to leave it as it is.

I propose to close the issue and make the UI test not depend on the div wrapper.

**Comment by sigdestad** [comment]
Ah.. Maybe it would be a "safer" solution to simply add another attribute instead of a whole div. How about data-portal-fragment="true"? Only added when in live edit?
