### ISSUE TITLE
Tab with Outbound Dependencies should be refreshed after version rollback

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#459]
1. Create new shortcut, select an image, save it 
2. Select another image in the shortcut, save it 
3. Click on the shortcut and open `Outbound Dependencies`
4. Go to the shortcut wizard, open `versions panel ` and rollback the previous version.

Bug:  `Outbound Dependencies` should be refreshed after version rollback

**wizard**: 
![image](https://user-images.githubusercontent.com/3728712/46402716-3c979400-c709-11e8-93e0-9a74e62fc960.png)

**In Outbound dependencies**:

![image](https://user-images.githubusercontent.com/3728712/46402761-576a0880-c709-11e8-8642-19c4f792dee0.png)

**Comment by ashklianko** [comment]
That was fixed in #456;
In this task I am fixing issue for a Outbound Dependencies section shown when content has no any dependencies: say you insert url into browser like **_admin/tool/com.enonic.xp.app.contentstudio/main#/outbound/1759b321-a367-44cc-96bd-b4bdbb6f9a97_**

But content with id from url might not have any dependencies already; In this case you'll see Dependencies Section open and spinner running in content grid;

Fixed by checking content's dependencies before routing to content studio inbound/outbound url;
