### ISSUE TITLE
Dependencies widget is not updated when 'Inbound Dependencies' was changed in the related content

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#553]
1. Create image-selector content in `Features`  (Do not close the wizard)
2. Create new shortcut and specify the 'image-selector content ' in `shortcut-target`
3. Go to grid 

**Bug**:
**Expected**: new added `Incoming Dependency` should appear in the widget 

**Actual:**
![image](https://user-images.githubusercontent.com/3728712/48774756-24d99680-ecdc-11e8-903c-b0c5ad5a9240.png)

When Refresh grid and select the content, Incoming dependency appears:

![image](https://user-images.githubusercontent.com/3728712/48774882-7d109880-ecdc-11e8-91d9-2d8f494165e9.png)

**Comment by alansemenov** [comment]
We already had a [similar bug](https://github.com/enonic/app-contentstudio/issues/374) and we decided we won't fix because of the reasons [described here](https://github.com/enonic/app-contentstudio/pull/391#issuecomment-425049887). Basically, in order to track appearance of a new incoming dependency we'd have to listen to update events of every single content item in the storage and for every such update we'd have to make an API request to check if this updated content has a reference to our content. This is too much just for the sake of updating the dependency widget.
